apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-q81d
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-q81d
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-q81d
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-q81d
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-q81d
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-vuov-tenant/rhtap-demo-app/hacbs-test-project-q81d@sha256:32877689f4366bec1e9acb1cb51e7a74cf1e6f47c3c7c4fdd4dba95af1a5bda5
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
